#!/usr/bin/env python3
"""
Watch the learned world model PLAY — the grid you see is generated entirely by
the neural net (fed its own output), not the engine. The real engine runs the
same steps only to print a [OK]/[drift] tag.

    <conda-python> poc\\watch_model.py [MAP] [steps]          # live animation
    <conda-python> poc\\watch_model.py [MAP] [steps] --still  # static filmstrip

Good "perfect" maps: CERULEAN_POKECENTER VIRIDIAN_NICKNAME_HOUSE DAYCARE
                     NAME_RATERS_HOUSE REDS_HOUSE_1F ROUTE_8_GATE
"""
import os
import sys
import time
import random
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rollout import load_model, predict
from pokeworld import World, DELTA

ARROW = {"up": "↑", "down": "↓", "left": "←", "right": "→"}
# prettier glyphs for display only (model still works on the raw chars)
PRETTY = {"#": "█", ".": "·", "@": "@", "D": "▙"}


def vt_on():                                   # enable ANSI on Windows terminals
    if os.name == "nt":
        import ctypes
        k = ctypes.windll.kernel32
        k.SetConsoleMode(k.GetStdHandle(-11), 7)


def show(grid):
    out = []
    for ln in grid.split("\n"):
        out.append("    " + "".join(PRETTY.get(c, c) for c in ln))
    return "\n".join(out)


def main():
    still = "--still" in sys.argv
    argv = [a for a in sys.argv[1:] if not a.startswith("--")]
    mapc = next((a for a in argv if not a.isdigit()), "CERULEAN_POKECENTER")
    steps = int(next((a for a in argv if a.isdigit()), 40))
    model, stoi, itos, T = load_model()
    vt_on()
    w = World(mapc)
    w.spawn_main()                             # largest walkable region (not a pocket)
    sim = w.render_plain()
    rng = random.Random(7)
    for t in range(1, steps + 1):
        a = rng.choice(list(DELTA))
        sim = predict(model, sim, a, stoi, itos, T)
        w.step(a)
        ok = (w.m.const == mapc and sim == w.render_plain())
        tag = "OK — matches engine" if ok else "drift"
        header = ("  %s   step %3d   action %s   [%s]"
                  % (mapc, t, ARROW[a], tag))
        if still:
            print(header + "\n" + show(sim) + "\n")
        else:
            print("\033[2J\033[H", end="")     # clear screen, home
            print("\n  🧠 this screen is generated by the neural net "
                  "(it is running the game)\n")
            print(header + "\n\n" + show(sim))
            sys.stdout.flush()
            time.sleep(0.18)
    if not still:
        print("\n  done.")


if __name__ == "__main__":
    main()
